### ISSUE TITLE
github trigger node complains about running on localhost

### ISSUE THREAD

**Issue by einSelbst** [sarveshwarge/n8n-heroku#13]
Hey!
Great project!

I tried to deploy n8n to heroku and importet my stuff. Everything went fine so far except that the github trigger node complains with the following message:

```
Problem running workflow
There was a problem running the workflow:
The Webhook can not work on "localhost". Please, either setup n8n on a custom domain or start with "--tunnel"!
```

Of course, I got the same issue when running my workflow locally and fixed it by running `n8n start -tunnel` but now that it runs on heroku I need to tell n8n about it's domain. 
I tried adding 2 env vars called `DOMAIN_NAME` and `SUBDOMAIN` and used the `herokuapp.com` and my app-name as the subdomain as given in the heroku ui, but the error persists.
I wonder if you have an idea how to solve it.

Thank you!

**Comment by sarveshpro** [comment]
Can you try setting `N8N_HOST` to app-name.herokuapp.com

**Comment by einSelbst** [comment]
Thank you @sarveshwarge ! That solved it.

**Comment by einSelbst** [comment]
Quick follow up: I had more issues with the webhook url (http instead of https & a port was appended). I did fix this by setting `WEBHOOK_TUNNEL_URL` to `https://app-name.herokuapp.com/` (of course, replacing app-name) so finally the correct Webhook for github was created.

**Comment by sarveshpro** [comment]
Glad to know your webhook is working now!
