### ISSUE TITLE
n8n is on 0.0.130 now and not 0.0.96

### ISSUE THREAD

**Issue by vongohren** [sarveshwarge/n8n-heroku#27]
Any plan to upgrade?

**Comment by jasteyn07** [comment]
Easy to fix, simply edit your forked image dockerfile. from 
ARG N8N_VERSION=0.98.0 
to 
ARG N8N_VERSION=0.132.0

Your installation should update to the new ver

**Comment by vongohren** [comment]
I know of that but there might be other repricautions. But I ended up running my own instalation and setup instead
