### ISSUE TITLE
Can't deploy to Heroku:   python (no such package):

### ISSUE THREAD

**Issue by dr-data** [sarveshwarge/n8n-heroku#31]
Can't deploy to Heroku:

Following error in the log during deployment:

Step 5/9 : RUN apk --update add --virtual build-dependencies python build-base && 	npm_config_user=root npm install -g n8n@${N8N_VERSION} && 	apk del build-dependencies
 ---> Running in 28471aa3149c
ERROR: unable to select packages:
  python (no such package):
    required by: build-dependencies-20211027.192635[python]
The command '/bin/sh -c apk --update add --virtual build-dependencies python build-base && 	npm_config_user=root npm install -g n8n@${N8N_VERSION} && 	apk del build-dependencies' returned a non-zero code: 2

**Comment by TheFSilverSP** [comment]
Got the exact same error...
`Step 5/9 : RUN apk --update add --virtual build-dependencies python build-base && 	npm_config_user=root npm install -g n8n@${N8N_VERSION} && 	apk del build-dependencies
 ---> Running in 0ea89fbd8c88
ERROR: unable to select packages:
  python (no such package):
    required by: build-dependencies-20211030.153459[python]
The command '/bin/sh -c apk --update add --virtual build-dependencies python build-base && 	npm_config_user=root npm install -g n8n@${N8N_VERSION} && 	apk del build-dependencies' returned a non-zero code: 2`

**Comment by TheFSilver** [comment]
Solved this issue by updating Dockerfile line 14 as follows :
`RUN apk --update add --virtual build-dependencies python3 build-base && \`

You have to specify python3 ;-)

If you run into an anonymousId or userId error from the telemetry feature, just disable that feature in the start.sh file as follows :
`export N8N_DIAGNOSTICS_ENABLED=false`

Just add that line before the last one !
