### ISSUE TITLE
Is this the latest N8N version

### ISSUE THREAD

**Issue by jay377** [sarveshwarge/n8n-heroku#33]
Hellom

I was wondering how up to date this is as I saw it on an old stackoverflow thread, will this let me easily (I am not a developer) install the latest N8N self host version on Heroku currently? Thanks

**Comment by nosovk** [comment]
Yep, currently the latest version will be deployed, but when you install it into Heroku you will create a copy of that repo, and you will have to do additional manipulations to get any updates,
