### ISSUE TITLE
Heruko button fails in creating a new app

### ISSUE THREAD

**Issue by TechMasterElvy** [sarveshwarge/n8n-heroku#36]
<img width="662" alt="image" src="https://user-images.githubusercontent.com/40030320/146045129-a17583cf-bede-4582-8ee5-ab18a052c031.png">

**Comment by nosovk** [comment]
I created a new deployment, and everything works fine. It may be related to setting you provided on previous installation step.

**Comment by TechMasterElvy** [comment]
I didnt notice the last error, it was showing because I was creating the app under a team, not my personal account
Just created it into my personal account and then moved it to team which auto-upgraded the dyno
