### ISSUE TITLE
How to update?

### ISSUE THREAD

**Issue by backendoadmin** [sarveshwarge/n8n-heroku#39]
Hello!

First of all, thank you for your nice job, it's really a must-have. 

I have deployed successfully with the Deploy on Heroku button after I forked your repo. 

I have some other apps on Heroku and for those I use actions. (there are 2 actions, one for installation and, the second for update). 

My question is that after I pull updates from upstream to my repo. How can I update the app easily on Heroku?

If I push a Deploy on Heroku its tries to start a new one, instead of updating the existing setup. 

Sorry for this beginner question, but maybe it's also helpful for someone else too.

**Comment by nosovk** [comment]
You need to update your repo from upstream first,
Then at heroku you need to point git to your repo with fork. Then updates will be applied to yours heroku instance.

**Comment by backendoadmin** [comment]
It worked. Thank you!
