### ISSUE TITLE
Customize n8n

### ISSUE THREAD

**Issue by liusiyong** [sarveshwarge/n8n-heroku#43]
Hello,

I have made some local customizations to n8n, and I would like to deploy from my own repo instead of the n8n repo.

However, I am not quite sure how I should modify the Dockerfile to do so.

Any suggestions would be much appreciated. Thanks!

**Comment by nosovk** [comment]
You need to make a fork of repo. Put your changes into forked repo

**Comment by liusiyong** [comment]
I did that, and also modified the DockerFile.
[DockerFile.txt](https://github.com/sarveshpro/n8n-heroku/files/8408231/D

I am able to deploy to Heroku, but I got an error when trying to start the app.
[n8n-har-logs-1649062762747.txt](https://github.com/sarveshpro/n8n-heroku/files/8408250/n8n-har-logs-1649062762747.txt)
ockerFile.txt)

**Comment by liusiyong** [comment]
I did that, and also modified the DockerFile.
[DockerFile.txt](https://github.com/sarveshpro/n8n-heroku/files/8408267/DockerFile.txt)

I am able to deploy to Heroku, but I got an error when trying to start the app.
[n8n-har-logs-1649062762747.txt](https://github.com/sarveshpro/n8n-heroku/files/8408268/n8n-har-logs-1649062762747.txt)

**Comment by nosovk** [comment]
It's not look like you use Dockerfile from that repo.
docker-entrypoint.sh - we don't use it.

**Comment by liusiyong** [comment]
Thanks
